BulkyBook/Areas/Admin/Controllers/CoverTypeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BulkyBook.DataAccess.Repository.IRepository;
using BulkyBook.Models;
using BulkyBook.Utility;
using Dapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BulkyBook.Areas.Admin.Controllers
{
    [Area("Admin")]

    [Authorize(Roles = SD.Role_Admin)]
    public class CoverTypeController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public CoverTypeController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            var coverTypes = _unitOfWork.SP_Call.List<CoverType>(SD.Proc_CoverType_GetAll);
            return View(coverTypes);
        }

        public IActionResult Upsert(int? id) {
            var coverType = new CoverType();
            
            if (id != null) {
                var parameter = new DynamicParameters();
                parameter.Add("@Id", id);
                coverType = _unitOfWork.SP_Call.OneRecord<CoverType>(SD.Proc_CoverType_Get, parameter);
            }

            return View(coverType);

        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(CoverType coverType) {
            if (!ModelState.IsValid) {
                return View();
            }

            var parameter = new DynamicParameters();
            parameter.Add("@Name", coverType.Name);
            if (coverType.Id == 0) {
                _unitOfWork.SP_Call.Execute(SD.Proc_CoverType_Create, parameter);
            } else {
                parameter.Add("@Id", coverType.Id);
                _unitOfWork.SP_Call.Execute(SD.Proc_CoverType_Update, parameter);
            }
            _unitOfWork.Save();
            return RedirectToAction(nameof(Index));
            
        }

        public IActionResult Delete(int id) {
            var parameters = new DynamicParameters();
            parameters.Add("@Id", id);
            var coverType = _unitOfWork.SP_Call.OneRecord<CoverType>(SD.Proc_CoverType_Get, parameters);
            if (coverType == null) {
                return NotFound();
            }

            _unitOfWork.SP_Call.Execute(SD.Proc_CoverType_Delete, parameters);
            _unitOfWork.Save();


            return RedirectToAction(nameof(Index));
        }
    }
}

BulkyBook/Areas/Admin/Views/CoverType/Index.cshtml
@model List<BulkyBook.Models.CoverType>

@{
    ViewData["Title"] = "Index";
}

<br />

<div class="row">
    <div class="col-6">
        <h2 class="text-primary">Cover Type List</h2>
    </div>
    <div class="col-6 text-right">
        <a class="btn btn-primary" asp-area="Admin" asp-controller="CoverType" asp-action="Upsert">
            <em class="fas fa-plus"></em>&nbsp; Create Cover Type
        </a>
    </div>
</div>

<br />

<div class="p-4 border rounded">
    @if (Model.Count > 0)
    {
        <table id="tblData" class="table table-striped table-bordered w-100">
            <thead class="thead-dark">
                <tr class="table-info">
                    <th>Name</th>
                    <th>Actions</th>
                </tr>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.Name</td>
                        <td>
                            <a asp-action="Upsert" asp-route-id="@item.Id">Edit</a>
                            <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                        </td>
                    </tr>


                }
            </thead>
        </table>
    }
    else
    {
        <div class="alert alert-warning">No Cover Types found</div>
    }
</div>

BulkyBook/Areas/Admin/Views/CoverType/Upsert.cshtml
@model BulkyBook.Models.CoverType
@{
    ViewData["Title"] = "Create";
    var title = "Create CoverType";
    if (Model.Id != 0) {
        title = "Update CoverType";
    }
}

<h1>@title</h1>


<div class="row">
    <div class="col-md-12">
        <form method="post" >
            
            <div class="form-group">
                <label asp-for="Name"></label>
                <input asp-for="Name" class="form-control"/>
                <span class="text-danger" asp-validation-for="Name"></span>
            </div>

            <div>
                @if (Model.Id != 0)
                {
                    <partial name="_EditAndBackToList" model="@Model.Id"/>
                }
                else { 
                    <partial name="_CreateAndBackToList" />
                }
              
            </div>
        </form>
    </div>
</div>