BulkyBook/Areas/Admin/Controllers/CompanyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BulkyBook.DataAccess.Repository.IRepository;
using BulkyBook.Models;
using BulkyBook.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BulkyBook.Areas.Admin.Controllers
{
    [Area("Admin")]

    [Authorize(Roles =SD.Role_Admin+","+SD.Role_Employee)]
    public class CompanyController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public CompanyController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            var companies = _unitOfWork.Company.GetAll();
            return View(companies);
        }

        public IActionResult Upsert(int? id) {
            var company = new Company();
            if (id != null) {
                company = _unitOfWork.Company.Get(id.GetValueOrDefault());
                if (company == null) {
                    return NotFound();

                }
            }

            return View(company);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(Company company) {
            if (!ModelState.IsValid) {
                return View(company);
            }

            if (company.Id != 0)
            {
                
                //update
                _unitOfWork.Company.Update(company);
            }
            else
            {
                _unitOfWork.Company.Add(company);
            }

            _unitOfWork.Save();
            return RedirectToAction(nameof(Index));
        }
    }
}

BulkyBook/Areas/Admin/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using BulkyBook.DataAccess.Repository.IRepository;
using BulkyBook.Models;
using BulkyBook.Models.ViewModels;
using BulkyBook.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BulkyBook.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles =SD.Role_Admin)]
    public class ProductController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public ProductController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _webHostEnvironment = webHostEnvironment;
                
        }
        public IActionResult Index()
        {
            var Product = _unitOfWork.Product.GetAll(includeProperties: "Category,CoverType");
            return View(Product);
        }

        public IActionResult Upsert(int? id) {
            var ProductViewModel = new ProductViewModel() {
                Product = new Product(),
                CategoryList = _unitOfWork.Category.GetAll().Select(i => new SelectListItem() {
                    Text = i.Name,
                    Value = i.Id.ToString()

                }),
                CoverTypeList = _unitOfWork.CoverType.GetAll().Select(i => new SelectListItem()
                {
                    Text = i.Name,
                    Value = i.Id.ToString()

                })
            };

            if (id == null)
            {
                return View(ProductViewModel);

            }
            else
            {
                ProductViewModel.Product = _unitOfWork.Product.Get(id.GetValueOrDefault());
                if (ProductViewModel.Product == null) {
                    return NotFound();
                }
                return View(ProductViewModel);
            }

        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(ProductViewModel ProductVM) {
            if (!ModelState.IsValid) {
                ProductVM.CategoryList = _unitOfWork.Category.GetAll().Select(i => new SelectListItem()
                {
                    Text = i.Name,
                    Value = i.Id.ToString()

                });
                ProductVM.CoverTypeList = _unitOfWork.CoverType.GetAll().Select(i => new SelectListItem()
                {
                    Text = i.Name,
                    Value = i.Id.ToString()

                });
                return View(ProductVM);
            }

            //get wwwroot folder path
            var webRootPath = _webHostEnvironment.WebRootPath;

            //getfiles uploaded in form
            var files = HttpContext.Request.Form.Files;


            if (files.Count > 0) {
                //files present
                var fileName = DateTimeOffset.UtcNow.ToUnixTimeSeconds().ToString();
                var uploadPath = Path.Combine(webRootPath, @"images\products");
                var fileExtension = Path.GetExtension(files[0].FileName);

                //upload file
                if (ProductVM.Product.ImageUrl != null)
                {
                    //file already exists need to delete file first


                    //get existed image path
                    var imagePath = Path.Combine(webRootPath, ProductVM.Product.ImageUrl.TrimStart('\\'));
                    if (System.IO.File.Exists(imagePath)) {
                        System.IO.File.Delete(imagePath);
                    }

                }

                //upload file to the image path
                using (var fileStreams = new FileStream(Path.Combine(uploadPath, fileName + fileExtension), FileMode.Create)) {

                    files[0].CopyTo(fileStreams);
                }

                ProductVM.Product.ImageUrl = @"\images\products\" + fileName + fileExtension;

            } else {
                if (ProductVM.Product.Id != 0) {
                    var objFromDb = _unitOfWork.Product.Get(ProductVM.Product.Id);
                    ProductVM.Product.ImageUrl = objFromDb.ImageUrl;
                }
            }

           

            if (ProductVM.Product.Id == 0) {
                //Adding product
                _unitOfWork.Product.Add(ProductVM.Product);
            } else {
                _unitOfWork.Product.Update(ProductVM.Product);
            }
            _unitOfWork.Save();

            return RedirectToAction(nameof(Index));
        }
    }
}

BulkyBook/Areas/Admin/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BulkyBook.DataAccess.Repository.IRepository;
using Microsoft.AspNetCore.Mvc;

namespace BulkyBook.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class UserController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public UserController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            var users = _unitOfWork.ApplicationUser.getUserWithRole();
            return View(users);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult LockUser() {
            var id =  HttpContext.Request.Form["Id"].ToString();
            var userdetails = _unitOfWork.ApplicationUser.GetUserById(id);

            if (userdetails != null) {
                var todaysDate = DateTimeOffset.Now;
                if (userdetails.LockoutEnd == null || userdetails.LockoutEnd <= todaysDate)
                {
                    userdetails.LockoutEnd = DateTimeOffset.Now.AddYears(1000);
                }
                else
                {
                    userdetails.LockoutEnd = null;
                }

                _unitOfWork.ApplicationUser.Update(userdetails);
                _unitOfWork.Save();
            }
            return RedirectToAction(nameof(Index));

        }
    }
}

BulkyBook/ViewComponents/ShoppingCartCountViewComponent.cs
using BulkyBook.DataAccess.Repository.IRepository;
using BulkyBook.Utility;
using BulkyBook.Utility.Extensions;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace BulkyBook.ViewComponents
{
	public class ShoppingCartCountViewComponent : ViewComponent
	{
		private readonly IUnitOfWork _unitOfWork;

		public ShoppingCartCountViewComponent(IUnitOfWork unitOfWork)
		{
			_unitOfWork = unitOfWork;

		}

		public IViewComponentResult Invoke()
		{
			var claimsIdentity = (ClaimsIdentity)User.Identity;
			var userId = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
			var sessionCount = HttpContext.Session.GetObject<string>(SD.ssShoppingCart);
			if (userId != null)
			{
				if (sessionCount == null || sessionCount == "")
				{
					var count = _unitOfWork.ShoppingCart.GetAll(u => u.ApplicationUserId == userId.Value).Count();
					HttpContext.Session.SetObject(SD.ssShoppingCart, count);
					sessionCount = count.ToString();
				}
			}
			else
			{
				sessionCount = 0.ToString();
			}




			return View("Default", sessionCount);
		}
	}
}

BulkyBook/Views/Shared/_CreateAndBackToList.cshtml
<div>
    <button type="submit" class="btn btn-primary">Create</button>
    <a asp-action="Index" class="btn btn-default">Back to List</a>
</div>

BulkyBook/Views/Shared/_EditAndBackToList.cshtml
@model int

<div>
    <button type="submit" class="btn btn-primary" asp-route-id="@Model">Update</button>
    <a asp-action="Index" class="btn btn-default">Back to List</a>
</div>

BulkyBook/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BulkyBook</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BulkyBook</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @if (User.IsInRole(BulkyBook.Utility.SD.Role_Admin))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Content Management
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="Index">Category</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="CoverType" asp-action="Index">CoverType</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Product" asp-action="Index">Products</a>
                                </div>
                            </li>
                        }

                        @if (User.IsInRole(BulkyBook.Utility.SD.Role_Admin) || User.IsInRole(BulkyBook.Utility.SD.Role_Employee))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown2" role="button"
                                   data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Company/User
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown2">
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Company" asp-action="Index">Company</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="User" asp-action="Index">User</a>
                                </div>
                            </li>
                        }

                        @await Component.InvokeAsync("ShoppingCartCount")
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-primary">
        <div class="container text-white">
            &copy; 2020 - BulkyBook - <a asp-area="" asp-controller="Home" asp-action="Privacy" class="text-white">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script src="https://kit.fontawesome.com/e19c476714.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>